config/routes.rb
Rails.application.routes.draw do

  root "authors#index"

  get '/root', to: 'authors#index'

  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'

  resources :authors
  resources :books
  resources :users

  resource :session
end

app/models/author.rb
class Author < ActiveRecord::Base
	validates :first_name, presence: true
	validates :last_name, presence: true
	
	has_many :publications, dependent: :destroy
	has_many :books, through: :publications

	def full_name
		"#{first_name} #{last_name}"
	end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :publisher
  has_many :publications, dependent: :destroy
  has_many :authors, through: :publications

  validates :title, presence: true
  validates :isbn, presence: true
  validates :description, presence: true
  validates :published_at, presence: true
  
  validates :page_count, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 0.0 }

  mount_uploader :book_cover, BookCoverUploader
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base

	has_many :books

	validates :name, presence: true
	validates :name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	validates :first_name, :last_name, :email, presence: true

	def full_name
		"#{first_name} #{last_name}"
	end

	def self.authenticate(email, password)
		#require 'pry';binding.pry
		user = User.find_by(email: email)
		user && user.authenticate(password)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	before_action :set_author, except: [:index, :new, :create]

	def index

	end

	def show
		#require 'pry';binding.pry
	end
 
	def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)
		if @author.save
			flash[:success] = "Author has been created"

			redirect_to @author
		else
			flash[:danger] = "Author has not been created"
			render :new
		end
	end

	def edit
	end

	def update
		if @author.update(author_params)
			flash[:success] = "Author has been updated"
			redirect_to @author
		else
			flash[:danger] = "Author has not been updated"
			render :edit
		end
	end

	def destroy
		@author.destroy
		flash[:success] = "Author has been deleted"
		redirect_to authors_path
	end

	private

	def author_params
		params.require(:author).permit(:first_name, :last_name)
	end

	def set_author
		@author = Author.find(params[:id])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_books, except: [:index, :new, :create]

	def index
		@books = Book.all
	end

	def show
		
	end

	def new
		@book = Book.new
		@publishers = Publisher.all
		@authors = Author.all
	end

	def create
		@book = Book.new(book_params)

		if @book.save
			flash[:success] = "Book has been created"
			redirect_to @book
		else
			flash[:danger] = "Book has not been created"
			render :new
		end
	end

	private

	def book_params
		params.require(:book).permit(:title, :isbn, :description, :published_at, :publisher_id, :page_count, :price, :book_cover)
	end

	def set_books
		@book = Book.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		redirect_to root_path if current_user
	end

	def create
		if user = User.authenticate(params[:email], params[:password])
			session[:user_id] = user.id
			flash[:success] = "Sign in successful"
			redirect_to root_path
		else
			flash.now[:danger] = "Invalid email/password combination"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have been signed out"
		redirect_to root_path
	end

	private

	def session_params
		params.require(:session).permit()
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, except: [:index, :new, :create]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			flash[:success] = "User has been created"
			redirect_to @user
		else
			flash[:danger] = "User could not be saved"
			render :new
		end
	end

	def show
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>

	<div id="form-group">
		<%= f.label :first_name %>
		<%= f.text_field :first_name, class: "form-control" %>
	</div>

	<div id="form-group">
		<%= f.label :last_name %>
		<%= f.text_field :last_name, class: "form-control" %>
	</div>
	<%= f.submit "Create Author", class: "btn btn-primary" %>

<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render "form" %>

<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/authors/new.html.erb
<h1>New Author Entry</h1>

<%= render 'form' %>

<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>

	<div id="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>
	</div>

	<div id="form-group">
		<%= f.label :isbn %>
		<%= f.text_field :isbn, class: "form-control" %>
	</div>

	<div id="form-group">
		<%= f.label :page_count %>
		<%= f.text_field :page_count, class: "form-control" %>
	</div>

	<div id="form-group">
		<%= f.label :price %>
		<%= f.text_field :price, class: "form-control" %>
	</div>

	<div id="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: "form-control" %>
	</div>

	<div id="form-group">
		<%= f.label :published_at %>
		<%= f.text_field :published_at, class: "form-control" %>
	</div>

	<div id="form-group">
		<%= label_tag 'publisher', 'Publisher' %>
		<%= f.select :publisher_id, @publishers.map { |p| [p.name, p.id] },
						prompt: 'Select a publisher', class: 'form-control' %>
	</div>

	<div id="form-group">
		<%= f.label "Book Cover" %>
		<%= f.file_field :book_cover, placeholder: 'Book Cover', class: 'form-control' %>
	</div>

	<div id="form-group">
		<%= f.collection_check_boxes :author_ids, @authors, :id, :full_name, class: "form-control" %>
	</div>

	<br>
	<%= f.submit "Create Book", class: "btn btn-primary" %>

<% end %>
<br>

app/views/books/new.html.erb
<h1>New Book Entry</h1>

<%= render "form" %>

<%= link_to "Cancel", root_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookstoreApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<%= render "shared/header" %>

	<div class="container">
		<% flash.each do |name,msg| %>
			<%= content_tag(:div, msg, class: "alert-#{name}") %>
		<% end %>

		<%= yield %>		
	</div>

</body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BookStore", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Authors", authors_path %></li> 
        <li><%= link_to "Add New Author", new_author_path %></li>
        <li><%= link_to "Books", books_path %></li>
        <li><%= link_to "Add New Book", new_book_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Sign up", new_user_path %> </li>
        <li> <%= link_to "Sign in", signin_path %> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

	<div id="form-group">
		<%= f.label :first_name %>
		<%= f.text_field :first_name, class: "form-control" %>
	</div>

	<div id="form-group">
		<%= f.label :last_name %>
		<%= f.text_field :last_name, class: "form-control" %>
	</div>

	<div id="form-group">
		<%= f.label :email %>
		<%= f.text_field :email, class: "form-control" %>
	</div>

	<div id="form-group">
		<%= f.label :password %>
		<%= f.text_field :password, class: "form-control" %>
	</div>

	<div id="form-group">
		<%= f.label :password_confirmation %>
		<%= f.text_field :password_confirmation, class: "form-control" %>
	</div>

	<%= f.submit "Create User" %>

<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form" %>
<br>
<%= link_to "Cancel", root_path, class: "btn btn-default" %>